services:
  app:
    build: .
    ports:
      - "8888:8888"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/nurseryapp?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    depends_on:
      - db
    networks:
      - nursery-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: nurseryapp
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nursery-network




volumes:
  mysql-data:

networks:
  nursery-network:
