pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                // Checkout the code from the repository
                git 'https://github.com/haouari-mohamed/Nursery-Fil-Rouge-Project.git'
            }
        }

     stage('Build with Maven') {
         steps {
             script {

                 bat 'mvn clean package'
             }
         }
     }

        stage('Build Docker Image') {
            steps {
                // Build Docker images from docker-compose file
                script {
                    sh 'docker-compose build'
                }
            }
        }

        stage('Run Docker Containers') {
            steps {
                // Run the application using docker-compose
                script {
                    sh 'docker-compose up -d'
                }
            }
        }

        stage('Test') {
            steps {
                // Optional: Run tests
                script {
                    sh 'mvn test'
                }
            }
        }

        stage('Cleanup') {
            steps {
                // Stop and remove Docker containers
                script {
                    sh 'docker-compose down'
                }
            }
        }
    }

    post {
        always {
            // Always clean up
            cleanWs()
        }
    }
}
